//API1 

GET http://localhost:3000/movies/

### 
//API2 
POST http://localhost:3000/movies/
Content-Type: application/json 
{
    "directorId": 6,
    "movieName": "Jurassic Park",
    "leadActor": "Jeff Goldbl"
}

### 
//API3 
GET http://localhost:3000/movies/46/ 

###
//API4 
PUT http://localhost:3000/movies/46/
Content-Type: application/json 
{
    "directorId": 24,
    "movieName": "Thor",
    "leadActor": "Christopher Hemsworth"
}

### 
//API5 

DELETE http://localhost:3000/movies/46/

###
//API6 
GET http://localhost:3000/directors/

###
//API7 
GET http://localhost:3000/directors/5/movies/